### PR TITLE
Cleaning up NuGet dependencies and sending ack emails in Simulation Mode

### PR DESCRIPTION
**Pull request by mbmccormick**
Doing two things with this pull request:

1. **Removing the NuGet.targets and cleaning up the NuGet references.** From a fresh clone of this repository, I ran into several issues trying to build. The first was a complaint about the NuGet.targets (what does this do? is it needed with the package manager in Visual Studio 2013?) and the second was that Microsoft.TeamFoundation.WorkItemTracking.Proxy could not be found at runtime. After some time trying to fix this DLL reference, I just removed the NuGet packages and referenced the same libraries from the GAC. The DLLs seem to be included by default with VS2013.
2. **Made it so that ack emails are sent even in Simulation Mode.** This makes it easy to play with the email templates and ensure that the email processing is working before going live with TFS/VSO.

Curious to see if f4fd6100d377106cf6acfabadf8baf1af5c3a07b works on your machine. :smile:

Awesome project, many thanks!

### CODE REVIEW

**Comment by hershi** [comment]
Thanks for sending this! 
I'll review and merge in the next few days

**Comment by mbmccormick** [comment]
Added another small change to the ##MessageBodyWithSender special value: extra new line character between the sender information and adding a space between the sender's name and their email address. :smile:

**Comment by hershi** [comment]
Hi,
I'm reviewing the changes, and saw that in you added the following to the app.config. Can you clarify why that configuration is needed (ideally, should be documented in the file):
  <system.web>
+    <membership defaultProvider="ClientAuthenticationMembershipProvider">
+      <providers>
+        <add name="ClientAuthenticationMembershipProvider" type="System.Web.ClientServices.Providers.ClientFormsAuthent
+      </providers>
+    </membership>
+    <roleManager defaultProvider="ClientRoleProvider" enabled="true">
+      <providers>
+        <add name="ClientRoleProvider" type="System.Web.ClientServices.Providers.ClientRoleProvider, System.Web.Extensi
+      </providers>
+    </roleManager>
+  </system.web>
+</configuration>

**Comment by hershi** [comment]
Hi,
I'm reviewing the changes, and saw that in you added the following to the app.config. Can you clarify why that configuration is needed (ideally, should be documented in the file):

`  <system.web>

    <membership defaultProvider="ClientAuthenticationMembershipProvider">

      <providers>

        <add name="ClientAuthenticationMembershipProvider" type="System.Web.ClientServices.Providers.ClientFormsAuthent...

      </providers>

    </membership>

    <roleManager defaultProvider="ClientRoleProvider" enabled="true">

      <providers>

        <add name="ClientRoleProvider" type="System.Web.ClientServices.Providers.ClientRoleProvider, System.Web.Extensi...

      </providers>

    </roleManager>

  </system.web>
`

**Pull request merged**
