### PR TITLE
Add basic credential way to create bug and update TeamFoundation dependency dlls to nuget

### PR DESCRIPTION
**Pull request by yongxiu**
Add basic credential config to allow users to create bug.

Some times the this mail2bug service's owner may not be the admin of VSO, allowing use basic alternate authentication credentials is good for teams that need to run this service using a standalone service account.

Update to VS2015, remove dependency on VS2012 dlls, use nuget for all TeamFoundation dlls.

### CODE REVIEW

**Comment by hershi** [comment]
Would be happy to integrate the ability to use basic credentials.
The update to VS2015 I would rather hold off on - this will cause trouble to many people since not everyone have the latest and greatest VS installed.
For using nuget for VS binaries - I tried going that route and found that some binaries are just not available through these packages. This may have been rectified since, but I'm wondering if you tested that this works by deploying the build result on a computer that doesn't have VS installed?

**Comment by yongxiu** [comment]
The change to update to VS2015 is just one line in sln file: VisualStudioVersion = 14.0.23107.0, I just tried Visual Studio 2012, 2013 could still build this solution.

Yes, I just tested on a clean Windows Server 2012 with only default .net 4.5 installed, without any VS, it could run successfully(send email, create task), you may also update wiki after this PR.

**Comment by hershi** [comment]
Sounds good, thanks.
I'll take care of the pull request next time I'm online

**Comment by yongxiu** [comment]
ping

**Pull request merged**
